"""
    Arbeitsagentur Studiensuche API

    Eine der größten Datenbanken für Studienangebote in Deutschland durchsuchen.   Die Authentifizierung funktioniert über eine clientId:  **clientId:** infosysbub-studisu  Die clientId muss bei folgenden GET-requests an https://rest.arbeitsagentur.de/infosysbub/studisu/pc/v1/studienangebote  als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.studiensuche.model.response_items_inner_studienangebot_studienanbieter_logo import (
    ResponseItemsInnerStudienangebotStudienanbieterLogo,
)

from deutschland import studiensuche

globals()[
    "ResponseItemsInnerStudienangebotStudienanbieterLogo"
] = ResponseItemsInnerStudienangebotStudienanbieterLogo
from deutschland.studiensuche.model.response_items_inner_studienangebot_studienanbieter import (
    ResponseItemsInnerStudienangebotStudienanbieter,
)


class TestResponseItemsInnerStudienangebotStudienanbieter(unittest.TestCase):
    """ResponseItemsInnerStudienangebotStudienanbieter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseItemsInnerStudienangebotStudienanbieter(self):
        """Test ResponseItemsInnerStudienangebotStudienanbieter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseItemsInnerStudienangebotStudienanbieter()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
