"""
    Arbeitsagentur Studiensuche API

    Eine der größten Datenbanken für Studienangebote in Deutschland durchsuchen.   Die Authentifizierung funktioniert über eine clientId:  **clientId:** infosysbub-studisu  Die clientId muss bei folgenden GET-requests an https://rest.arbeitsagentur.de/infosysbub/studisu/pc/v1/studienangebote  als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.studiensuche.api.default_api import DefaultApi  # noqa: E501

from deutschland import studiensuche


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_studiensuche(self):
        """Test case for studiensuche

        Studiensuche  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
