"""
    Arbeitsagentur Studiensuche API

    Eine der größten Datenbanken für Studienangebote in Deutschland durchsuchen.   Die Authentifizierung funktioniert über eine clientId:  **clientId:** infosysbub-studisu  Die clientId muss bei folgenden GET-requests an https://rest.arbeitsagentur.de/infosysbub/studisu/pc/v1/studienangebote  als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.studiensuche.model.response_items_inner_studienangebot_abschlussgrad import (
    ResponseItemsInnerStudienangebotAbschlussgrad,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_hochschulart import (
    ResponseItemsInnerStudienangebotHochschulart,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_region import (
    ResponseItemsInnerStudienangebotRegion,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_studienanbieter import (
    ResponseItemsInnerStudienangebotStudienanbieter,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_studienform import (
    ResponseItemsInnerStudienangebotStudienform,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_studienmodelle_inner import (
    ResponseItemsInnerStudienangebotStudienmodelleInner,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_studienort import (
    ResponseItemsInnerStudienangebotStudienort,
)
from deutschland.studiensuche.model.response_items_inner_studienangebot_studientyp import (
    ResponseItemsInnerStudienangebotStudientyp,
)

from deutschland import studiensuche

globals()[
    "ResponseItemsInnerStudienangebotAbschlussgrad"
] = ResponseItemsInnerStudienangebotAbschlussgrad
globals()[
    "ResponseItemsInnerStudienangebotHochschulart"
] = ResponseItemsInnerStudienangebotHochschulart
globals()[
    "ResponseItemsInnerStudienangebotRegion"
] = ResponseItemsInnerStudienangebotRegion
globals()[
    "ResponseItemsInnerStudienangebotStudienanbieter"
] = ResponseItemsInnerStudienangebotStudienanbieter
globals()[
    "ResponseItemsInnerStudienangebotStudienform"
] = ResponseItemsInnerStudienangebotStudienform
globals()[
    "ResponseItemsInnerStudienangebotStudienmodelleInner"
] = ResponseItemsInnerStudienangebotStudienmodelleInner
globals()[
    "ResponseItemsInnerStudienangebotStudienort"
] = ResponseItemsInnerStudienangebotStudienort
globals()[
    "ResponseItemsInnerStudienangebotStudientyp"
] = ResponseItemsInnerStudienangebotStudientyp
from deutschland.studiensuche.model.response_items_inner_studienangebot import (
    ResponseItemsInnerStudienangebot,
)


class TestResponseItemsInnerStudienangebot(unittest.TestCase):
    """ResponseItemsInnerStudienangebot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseItemsInnerStudienangebot(self):
        """Test ResponseItemsInnerStudienangebot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseItemsInnerStudienangebot()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
